#!/usr/bin/env bash
set -e

# We have to accept 3 params:- owner, repo and PR number. Only PR Number is required.
# We have to fetch the data using github cli like so
# gh api /repos/{owner}/{repo}/pulls/{pull_number}/commits
# After doing that, we need to parse the data that's returned, which will be an array and then we can simply print all of the shas of the commit.

owner="{owner}"
repo="{repo}"
pull="-1"

# Parse Arguments
while [ $# -gt 0 ]; do
  case "$1" in
    --repo=*)
      repo="${1#*=}"
      ;;
    -R=*)
      repo="${1#*=}"
      ;;
    -P=*)
      pull="${1#*=}"
      ;;
    --pull=*)
      pull="${1#*=}"
      ;;
    -O=*)
      owner="${1#*=}"
      ;;
    --owner=*)
      owner="${1#*=}"
      ;;
    *)
      printf "***************************\n"
      printf "* Error: Invalid argument.*\n"
      printf "***************************\n"
      exit 1
  esac
  shift
done
if [ $pull == "-1" ]; then
  echo "Please provide a pull request number"
  exit 1
fi

echo $(gh api /repos/$owner/$repo/pulls/$pull/commits --paginate --jq ".[].sha")
